on: 
  workflow_call:

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Test reusable workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Echo ${{ inputs.FIRST_PHRASE }}
        run: |
          echo ${{ inputs.FIRST_PHRASE }}
      - name: Echo ${{ inputs.SECOND_PHRASE }}
        run: |
          echo ${{ inputs.SECOND_PHRASE }}
